platform:ios,'9.0'
use_frameworks!

#set_arc_compatibility_flag!
#inhibit_all_warnings!

target 'grsu.schedule' do
pod 'GoogleMaps'
pod 'Flurry-iOS-SDK/FlurrySDK'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'RAMAnimatedTabBarController', :git => 'https://github.com/zixzelz/animated-tab-bar.git', :branch => 'dev'
pod 'Fabric'
pod 'Crashlytics'

#Localizable strings generation
pod 'SwiftGen', '5.2.1'

pod 'ReactiveCocoa'

end

pod 'Armchair', '>= 0.3'

#Add the following in order to automatically set debug flags for armchair in debug builds
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'Armchair'
            target.build_configurations.each do |config|
                if config.name == 'Debug'
                    config.build_settings['OTHER_SWIFT_FLAGS'] = '-DDebug'
                    else
                    config.build_settings['OTHER_SWIFT_FLAGS'] = ''
                end
            end
        end
    end
end
