platform:ios,'9.0'
use_frameworks!

#set_arc_compatibility_flag!
#inhibit_all_warnings!

target 'grsu.schedule' do
pod 'GoogleMaps'
pod 'Flurry-iOS-SDK/FlurrySDK'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'RAMAnimatedTabBarController', :git => 'https://github.com/zixzelz/animated-tab-bar.git', :branch => 'dev'
#pod 'ServiceLayerSDK', :git => 'https://github.com/zixzelz/love-of-music', :tag => '0.0.1'
#pod 'ServiceLayerSDK/CoreData', :git => 'https://github.com/zixzelz/love-of-music', :tag => '0.0.1'
#pod 'ServiceLayerSDK/ServiceLayerUIKit', :git => 'https://github.com/zixzelz/love-of-music', :tag => '0.0.1'

pod 'ServiceLayerSDK', :path => '../../love-of-music/'
pod 'ServiceLayerSDK/CoreData', :path => '../../love-of-music/'
pod 'ServiceLayerSDK/ServiceLayerUIKit', :path => '../../love-of-music/'

pod 'Fabric'
pod 'Crashlytics'
#Localizable strings generation
pod 'SwiftGen', '5.2.1'

pod 'ReactiveCocoa'

pod 'Armchair', '>= 0.3'
end

target 'grsu.today' do
  pod 'ServiceLayerSDK', :path => '../../love-of-music/'
  pod 'ServiceLayerSDK/CoreData', :path => '../../love-of-music/'
  pod 'ServiceLayerSDK/ServiceLayerUIKit', :path => '../../love-of-music/'
  pod 'ReactiveCocoa'
end


#Add the following in order to automatically set debug flags for armchair in debug builds
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'Armchair'
            target.build_configurations.each do |config|
                if config.name == 'Debug'
                    config.build_settings['OTHER_SWIFT_FLAGS'] = '-DDebug'
                    else
                    config.build_settings['OTHER_SWIFT_FLAGS'] = ''
                end
            end
        end
    end
end
